<a href="https://colab.research.google.com/github/fayomiEsther82/ML-Learning-Notebooks/blob/main/01_NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [7]:
print(type(my_array))

<class 'numpy.ndarray'>


In [8]:
print(my_array[2])

3


In [9]:
print(my_array[3:7])

[4 5 6 7]


In [10]:
print(my_array[5:])

[ 6  7  8  9 10]


In [13]:
print(my_array[-3:])

[ 8  9 10]


In [14]:
new_array = my_array + 10
print(new_array)

[11 12 13 14 15 16 17 18 19 20]
